### ISSUE TITLE
error results in emtpy json file

### ISSUE THREAD

**Issue by rgevaert** [lvillani/vagrant-metadata#2]
Hi,

When vagrant-metadata incurs an error (e.g. emtpy directory in provider) 

```
+ vagrant-metadata
Traceback (most recent call last):
  File "/usr/local/bin/vagrant-metadata", line 87, in <module>
    main()
  File "/usr/local/bin/vagrant-metadata", line 61, in main
    json.dump(process_directory(".", metadata, args.force), f, indent=4)
  File "/usr/local/lib/python2.7/dist-packages/vagrant_metadata.py", line 61, in process_directory
    box = box_in(provider_dir)
  File "/usr/local/lib/python2.7/dist-packages/vagrant_metadata.py", line 84, in box_in
    raise BoxCountError("Was expecting exactly one box: %s" % path)
vagrant_metadata.BoxCountError: Was expecting exactly one box: ./1.0.1443518668/virtualbox
```

The resulting json file is empty.  It would be better leave the original json file untouched.

**Comment by lvillani** [comment]
Thanks for catching that, I'll see what I can do to fix it.

**Comment by rgevaert** [comment]
that would be very neat!

**Comment by lvillani** [comment]
Just pushed version 1.0.2 to PyPI.
